import express from "express";
import helmet from "helmet";
import cors from "cors";
import cookieParser from "cookie-parser";
import rateLimit from "express-rate-limit";
import { env } from "./config/env.js";
import authRoutes from "./routes/auth.js";
import contactRoutes from "./routes/contact.js";
import serviceRoutes from "./routes/services.js";
import projectRoutes from "./routes/projects.js";
import dashboardRoutes from "./routes/dashboard.js";
import { errorHandler,notFound } from "./middleware/error.js";

export const app=express();
app.disable("x-powered-by");
app.use(helmet({crossOriginResourcePolicy:{policy:"cross-origin"}}));
app.use(cors({origin:[env.FRONTEND_URL,env.ADMIN_URL],credentials:true,methods:["GET","POST","PATCH","DELETE","OPTIONS"],allowedHeaders:["Content-Type"]}));
app.use(express.json({limit:"100kb"}));
app.use(express.urlencoded({extended:false,limit:"20kb"}));
app.use(cookieParser());
app.use(rateLimit({windowMs:15*60*1000,max:300,standardHeaders:"draft-8",legacyHeaders:false}));
app.get("/api/health",(_req,res)=>res.json({success:true,status:"ok",service:"lunaro-api"}));
app.use("/api/auth",authRoutes);
app.use("/api/contact",contactRoutes);
app.use("/api/services",serviceRoutes);
app.use("/api/projects",projectRoutes);
app.use("/api/dashboard",dashboardRoutes);
app.use(notFound);
app.use(errorHandler);
